/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: 'concepts'}],
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  systemsSidebar: [{type: 'autogenerated', dirName: 'systems'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
  // docs: [
  //   {
  //     type: 'category',
  //     label: 'Tools',
  //     link: {type: 'doc', id: 'tools/intro'},
  //     items: [],
  //   },
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
